/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp4;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Luly2
 */
public class FormularioDeMaterias extends javax.swing.JInternalFrame {

    
    
    private HashSet<Materia> materias;
    /**
     * Creates new form FormularioDeMaterias
     */
    public FormularioDeMaterias(HashSet<Materia> materias) {
        initComponents();
        this.materias = materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLtitulo = new javax.swing.JLabel();
        jLcodigoMateria = new javax.swing.JLabel();
        jLnombreMateria = new javax.swing.JLabel();
        jLañoPertenece = new javax.swing.JLabel();
        jTFcodigo = new javax.swing.JTextField();
        jTFnombreMateria = new javax.swing.JTextField();
        jTFaño = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setPreferredSize(new java.awt.Dimension(450, 380));

        jLtitulo.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLtitulo.setText("Formulario de Materias");

        jLcodigoMateria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLcodigoMateria.setText("CODIGO DE MATERIA:");

        jLnombreMateria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLnombreMateria.setText("NOMBRE DE LA MATERIA:");

        jLañoPertenece.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLañoPertenece.setText("AÑO AL QUE PERTENECE:");

        jTFaño.addActionListener(this::jTFañoActionPerformed);

        jBguardar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jBguardar.setText("Guardar");
        jBguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar.addActionListener(this::jBguardarActionPerformed);

        jBnuevo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBnuevo.addActionListener(this::jBnuevoActionPerformed);

        jBsalir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jBsalir.setText("Salir");
        jBsalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBsalir.addActionListener(this::jBsalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jBnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLnombreMateria)
                                    .addComponent(jLcodigoMateria))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLañoPertenece)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFaño, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLtitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigoMateria)
                    .addComponent(jTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFnombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombreMateria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLañoPertenece)
                    .addComponent(jTFaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBnuevo)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFañoActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
       jTFcodigo.setText("");
       jTFnombreMateria.setText("");
       jTFaño.setText("");
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        int codigo = Integer.parseInt(jTFcodigo.getText());
        String nombreM = jTFnombreMateria.getText();
        int año = Integer.parseInt(jTFaño.getText());
        
        Materia materia = new Materia(codigo,nombreM,año);
       Menu.listaMaterias.add(materia);
       JOptionPane.showMessageDialog(this, "Materia guardada");
       
    }//GEN-LAST:event_jBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLañoPertenece;
    private javax.swing.JLabel jLcodigoMateria;
    private javax.swing.JLabel jLnombreMateria;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFaño;
    private javax.swing.JTextField jTFcodigo;
    private javax.swing.JTextField jTFnombreMateria;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
