/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4;

import java.awt.Color;
import java.util.HashSet;

/**
 *
 * @author Luly2
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    static HashSet<Alumno> alumnos = new HashSet<>();
    static HashSet<Materia> materias = new HashSet<>();
    public Menu() {
        initComponents();
      this.getContentPane().setBackground(new Color(51, 102, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jItAgAlumno = new javax.swing.JMenuItem();
        jMmateria = new javax.swing.JMenu();
        jItAgMateria = new javax.swing.JMenuItem();
        jMregistro = new javax.swing.JMenu();
        jItInscribir = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();
        jItSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");
        jMAlumno.addActionListener(this::jMAlumnoActionPerformed);

        jItAgAlumno.setText("Agregar Alumno");
        jItAgAlumno.addActionListener(this::jItAgAlumnoActionPerformed);
        jMAlumno.add(jItAgAlumno);

        jMenuBar1.add(jMAlumno);
        jMAlumno.getAccessibleContext().setAccessibleName("");

        jMmateria.setText("Materia");

        jItAgMateria.setText("Agregar Materia");
        jItAgMateria.addActionListener(this::jItAgMateriaActionPerformed);
        jMmateria.add(jItAgMateria);

        jMenuBar1.add(jMmateria);

        jMregistro.setText("Registro");

        jItInscribir.setText("Inscribir Alumno");
        jItInscribir.addActionListener(this::jItInscribirActionPerformed);
        jMregistro.add(jItInscribir);

        jMenuBar1.add(jMregistro);

        jMsalir.setText("Salir");

        jItSalir.setText("Salir");
        jItSalir.addActionListener(this::jItSalirActionPerformed);
        jMsalir.add(jItSalir);

        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   

    private void jItAgMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItAgMateriaActionPerformed
        escritorio.removeAll();
        FormularioDeMaterias fdm = new FormularioDeMaterias();
        fdm.setVisible(true);
        escritorio.add(fdm);
        escritorio.moveToFront(fdm);
        escritorio.revalidate();
        escritorio.repaint();
                
    }//GEN-LAST:event_jItAgMateriaActionPerformed

    private void jItInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItInscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItInscribirActionPerformed

    private void jItSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItSalirActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAlumnoActionPerformed

    private void jItAgAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItAgAlumnoActionPerformed
         escritorio.removeAll();
        FormularioDeAlumnos fda= new FormularioDeAlumnos();
        fda.setVisible(true);
        escritorio.add(fda);
        escritorio.moveToFront(fda);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_jItAgAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jItAgAlumno;
    private javax.swing.JMenuItem jItAgMateria;
    private javax.swing.JMenuItem jItInscribir;
    private javax.swing.JMenuItem jItSalir;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMmateria;
    private javax.swing.JMenu jMregistro;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables

    private void backgroundcolor() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
